source 'https://github.com/BJComponent/BJSpecs.git'
# 删除公有库，因为公有库有和私有库名字相同的库
source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!
platform :ios, '9.0'

target ‘FlowerField’ do 
  
  #pod 'FFSpecialKit', git:'https://github.com/BJComponent/FFSpecialKit.git'
#  pod 'FFAuthorKit', git:'https://github.com/BJComponent/FFAuthorKit.git'


  pod 'FFSpecialKit', '~> 0.1.7'
  pod 'FFAuthorKit', '~> 0.1.8'

  pod 'FFBase'
  pod 'FFUtils', git:'https://github.com/BJComponent/FFUtils.git'
  



end

