
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/BJComponent/BJSpecs.git'

use_frameworks!
platform :ios, '8.0' 
target ‘FlowerField’ do 
  
pod 'FFSpecialKit', git:'https://github.com/BJComponent/FFSpecialKit.git'
pod 'FFAuthorKit', git:'https://github.com/BJComponent/FFAuthorKit.git'

pod 'FFBase', :path => './FFBase'
#pod 'FFAuthorKit', '~> 0.1.6'

end

